---
title: "gtsummary in quarto"
format: html
execute:
  echo: false
---

```{r}
#| message: false
library(tidyverse)
library(gtsummary)
nlsy_cols <- c("glasses", "eyesight", "sleep_wkdy", "sleep_wknd",
               "id", "nsibs", "samp", "race_eth", "sex", "region",
               "income", "res_1980", "res_2002", "age_bir")
nlsy <- read_csv(here::here("data", "raw", "nlsy.csv"),
                 na = c("-1", "-2", "-3", "-4", "-5", "-998"),
                 skip = 1, col_names = nlsy_cols) |>
  mutate(region_cat = factor(region, labels = c("Northeast", "North Central", "South", "West")),
         sex_cat = factor(sex, labels = c("Male", "Female")),
         race_eth_cat = factor(race_eth, labels = c("Hispanic", "Black", "Non-Black, Non-Hispanic")),
         eyesight_cat = factor(eyesight, labels = c("Excellent", "Very good", "Good", "Fair", "Poor")),
         glasses_cat = factor(glasses, labels = c("No", "Yes")))
```

# Customization of `tbl_summary()`

```{r}
tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir))
```

```{r}
tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir),
  label = list(
    race_eth_cat ~ "Race/ethnicity",
    region_cat ~ "Region",
    eyesight_cat ~ "Eyesight",
    glasses ~ "Wears glasses",
    age_bir ~ "Age at first birth"
  ),
  missing_text = "Missing")
```

Description of another Table @tbl-other

```{r}
#| label: tbl-other
#| tbl-cap: "Other Table"
tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir))
```

There were a lot of people who slept (@tbl-one).

```{r}
#| message: false
#| label: tbl-one
#| tbl-cap: "Descriptive Statistics including sleep"

sleep_table <- tbl_summary(
  nlsy,
  by = region_cat,
  include = c(sex_cat, race_eth_cat,
              sleep_wkdy, sleep_wknd)) |>
	add_overall()

sleep_table
```

```{r}
median(nlsy$sleep_wknd, na.rm = TRUE)
```

```{r}
  med_sleep <- median(nlsy$sleep_wknd, na.rm = TRUE)
```


```{r}
#sleep_table$table_body
inline_text(sleep_table, variable = "sleep_wknd", column = "stat_0")

#inline_text(sleep_table, variable = "sex_cat", level = "Female", column = "stat_0")
```

In the sample, the average sleep on weekends was `r inline_text(sleep_table, variable = "sleep_wknd", column = "stat_0")`.
